### ISSUE TITLE
Mixpanel.Register() leads to ArgumentException on second call of same property.

### ISSUE THREAD

**Issue by SamLucyk** [rocktavious/mixpanel-unity#1]
The first time I call `Mixpanel.Register("TimeOfDay", "Morning")` it works correctly but if I run the app again and make the call to Register the same property like `Mixpanel.Register("TimeOfDay", "Morning")` or `Mixpanel.Register("TimeOfDay", "Night")` it leads to the following error.

`ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (.TKey key, .TValue value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
mixpanel.Mixpanel.Register (System.String key, System.Object value) (at Assets/Scripts/Mixpanel/MixpanelAPI.cs:95)`

I changed the the line in MixpanelAPI.cs from `props.Add(key, value)` to 'props[key] = value' and it fixed it for me.

**Comment by rocktavious** [comment]
@SamLucyk Ahh ya thats a good catch - i'll fix that up when i go in and fix distinct id.

**Comment by rocktavious** [comment]
Fixed as of commit de5a726979ab938a9566165fefae75dcfbaed359
