### ISSUE TITLE
Full Mixpanel Properties

### ISSUE THREAD

**Issue by SamLucyk** [rocktavious/mixpanel-unity#3]
I realized only a few of the Mixpanel-provided properties that were being sent in the original Library aren't sent in this one. I figure it will take some time but thought I'd just add this to document the difference.

Log-in Log with origninal Library:
![Full-Mix-Panel-Props](https://user-images.githubusercontent.com/11763213/55979661-bb452f00-5c60-11e9-885a-0bebc11bd9e9.png)

Log-in Log with current Library:
![Current-Mix-Panel-Props](https://user-images.githubusercontent.com/11763213/55979711-d021c280-5c60-11e9-80f6-eb21a13819ce.png)

**Comment by rocktavious** [comment]
Hmm i must have missed something in one of their C files thats specific to iOS devices - i'll circle back around their source and double check.

**Comment by rocktavious** [comment]
Ahh yep - https://github.com/mixpanel/mixpanel-unity/blob/5d4ee9aff10b5fed62e91a16e85d6bb8c4f3452f/native/source/mixpanel/detail/platform_helpers.cpp#L110

**Comment by rocktavious** [comment]
Looks like most of this information can be gotten from https://docs.unity3d.com/ScriptReference/SystemInfo.html

**Comment by SamLucyk** [comment]
Yeah System Info should give most of it - I feel some of the most valuable info is the Location data they send - just not sure how they are getting that

**Comment by SamLucyk** [comment]
So just figured out -> If you include the ip address in properties with an event then it calculates the geo location on the server-side. You also need to add ip=1 to the Build Url function for it to work.

See https://developer.mixpanel.com/docs/httphttp#section-special-properties-in-events and look under the parameter 'ip' for full details. 

The rest of system info I need I just retrieve from https://docs.unity3d.com/ScriptReference/SystemInfo.html as you suggested above.

**Comment by rocktavious** [comment]
@SamLucyk thats a good data point (and a great documentation find) - i'll hook that into my work on this to auto inject the IP.  I've got most of this done so far - just trying to finish the JSON library stuff before i roll the next version out.

**Comment by rocktavious** [comment]
@SamLucyk I just pushed a new commit to master that fixes this issue and implicitly attaches to every track.  The only things I couldn't find analogs of where "Brand" and "Manufacturer" - some of that data is bound up in https://docs.unity3d.com/ScriptReference/SystemInfo-deviceModel.html which i put under "Model"
But other then that i think everything should be there now - even the location data.

Here is an example:
![MixpanelTest](https://user-images.githubusercontent.com/735015/56073309-37c23580-5d67-11e9-9e98-2216af4ee0e4.png)

The lastest master branch should also fix the JSON stuff - i opted for a csharp native file so if there are problems its easy to go in an fix (at most it'll be a little less performant then newtonsoft but at least then it can compile to any unity platform and its only 500-ish lines so it'll be easy to susout any problems and fix them)  If you could test the latest master branch to make sure it fixes all your problems and let me know that would be great!!!

**Comment by rocktavious** [comment]
@SamLucyk any word on this - is it everything you expect?

**Comment by SamLucyk** [comment]
Sorry for the late reply @rocktavious been super busy! But yes it's all working since implementing about a month ago now. Thanks again for all the help!

**Comment by rocktavious** [comment]
@SamLucyk I've been having chats with mixpanel about accepting this fork as the new library.  One of the things they want to see is the default properties that come out of an iOS device track call with this library.  Could you upload a screenshot of what the latest version of this library emits?  I don't have an iOS device to test with.
