### ISSUE TITLE
Some issues on UWP

### ISSUE THREAD

**Issue by beber666** [rocktavious/mixpanel-unity#5]
Hello

Thanks for your fork on mix panel unity extension :-)
I've tried with UWP but i got this error
Assets/Mixpanel/Mixpanel/Editor/MixpanelSettingsEditor.cs(9,17): error CS0246: The type or namespace name `SettingsProvider' could not be found. Are you missing `System.Configuration' using directive?

**Comment by rocktavious** [comment]
@beber666 Which version of Unity are you using - the new fork is only compatible with unity 2018.3 or greater.

**Comment by rocktavious** [comment]
@beber666 any word on this?

**Comment by rocktavious** [comment]
@beber666 I'm going to close out this issue assuming its because you are using unity < 2018.3.  If thats not the case please comment back and we can reopen and debug.
